#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs -o size=256M tmpfs /tmp
mount UUID={{ BOOT_UUID }} /boot -o rw

mdev -s
clear

{{ EXTRA_INIT }}

echo 'Welcome to Bootlet!'
exec setsid cttyhack sh
