#!/bin/sh

mdev -s

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs -o size=256M tmpfs /tmp
mount -t efivarfs efivarfs /sys/firmware/efi/efivars
mount UUID={{ BOOT_UUID }} /boot -o rw

clear

{{ EXTRA_INIT }}

echo 'Welcome to Bootlet!'
setsid cttyhack sh

poweroff -f
